### ISSUE TITLE
Dataset download issue

### ISSUE THREAD

**Issue by Atharvavp** [cs-chan/ArtGAN#14]
The dataset link does not work.

Link: http://web.fsktm.um.edu.my/~cschan/source/ICIP2017/wikiart.zip

**Comment by joeltorby** [comment]
I can't download the data either. There is something wrong with the download link.

**Comment by akihiro-inui** [comment]
This is working but it is way larger.
https://archive.org/download/wikiart-dataset/wikiart.tar.gz

**Comment by cs-chan** [comment]
Dear all, we have updated the download link for WikiArt dataset.

**Comment by gspinaci** [comment]
Hi @cs-chan, The download link is not working, and the zip file in the Google Drive link seems corrupted.

```
zip -T wikiart.zip
wikiart/Baroque/rembrandt_woman-standing-with-raised-hands.jpg  bad CRC 3d470143  (should be 90cccc50)
  error:  invalid compressed data to inflate wikiart/Post_Impressionism/vincent-van-gogh_l-arlesienne-portrait-of-madame-ginoux-1890.jpg
test of wikiart.zip FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
```
Please can you point me towards the correct download procedure?
