### ISSUE TITLE
No module named 'layers'? How to train this on my own Dataset? 

### ISSUE THREAD

**Issue by ghost** [cs-chan/ArtGAN#2]
Also, how to run this ? Any instructions ?

**Comment by ghost** [comment]
![issue](https://user-images.githubusercontent.com/42616914/47076621-c58bf080-d21c-11e8-810e-8e4df6fb4a30.PNG)
I am facing this issue,does any one have any solutions to this ??

**Comment by ghost** [comment]
Plz update repository with instructions on How to run this code. That would be very helpful.

**Comment by ghost** [comment]
![screenshot from 2018-10-17 17-31-13](https://user-images.githubusercontent.com/42616914/47084960-c2036400-d232-11e8-81d3-92d1686406c4.png)

**Comment by ghost** [comment]
The cudnn used to compile this code is no longer available. The error says that cudnn 7.2.1 was used but I had cudnn 7.0.5 installed. Later, I searched for cudnn 7.2.1 for CUDA 9.0. NVIDIA has deleted it from the archives. cudnn 7.3 for CUDA 9.0 stops at tf.Session(). What to do ??

**Comment by willtwr** [comment]
You can train with your own dataset by preparing your dataset structure using the ingest*.py files as example.

We used pycharm to run the code in our own environmet, so its probably environment path problem. 
Please change the path accordingly, e.g. import layers -> import nn.layers

While, your other question is related to your installed libraries versions.
Please update your libraries.

**Comment by ghost** [comment]
I resolved all the other issues. Had to change import layers to nn.layesr and data.dataloader
But now I get 
"Default AvgPoolingOp only supports NHWC on device type CPU" while running CIFARGANAEsample.py 
![supports nhwc on device type cpu](https://user-images.githubusercontent.com/42616914/47128358-7ee6d680-d2ae-11e8-89c6-993f024d69fa.png)

and while trying to train CIFARGANAEtrick I get the following error 
![trick](https://user-images.githubusercontent.com/42616914/47128425-ba81a080-d2ae-11e8-8e6a-f697a5aa97f7.png)

is it due to environment used ?
I am using Ubuntu 16.04 LTS
Conda and Virtual Env. 
Python 2.7 
Latest versions of Neon and Aeon 
Tensorflow 1.10
CUDA 9.0
CuDnn 7.3.1 
what were the versions of Neon and Aeon for you ? 
Thanks in advance.

**Comment by ghost** [comment]
Some thing I forgot to mention : I am running this on 1050ti.
I found out that CPU can only handle NHWC while the data used here is NCHW on GPU.
do you have any idea why i am getting a traceback to 

2018-10-18 07:58:33.486367: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-18 07:58:33.624672: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
	 [[Node: Generator/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Generator/Tanh)]]
Traceback (most recent call last):
  File "CIFAR64GANAEsample.py", line 86, in <module>
    gen_img, gen_img128 = sess.run([samples, samples128])
  File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/user/Downloads/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
	 [[Node: Generator/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Generator/Tanh)]]

**Comment by sandys** [comment]
hi guys,
same question here. would really appreciate some help on how to run this
