### ISSUE TITLE
Post_Impressionism/vincent-van-gogh_l-arlesienne-portrait-of-madame-ginoux-1890.jpg is broken

### ISSUE THREAD

**Issue by sotte** [cs-chan/ArtGAN#4]
Hi!

It seems that `wikiart/Post_Impressionism/vincent-van-gogh_l-arlesienne-portrait-of-madame-ginoux-1890.jpg` is broken. Can you verify that your file is also broken?

Maybe it's just my downloaded zip. Do you have the md5 of the zip file?

![image](https://user-images.githubusercontent.com/79138/48716728-3d807880-ec18-11e8-97a2-a91bccca2c4a.png)

**Comment by willtwr** [comment]
Hi,

The paintings look fine in our machine during training.
We will try to look into the zip file and see if there is broken images when we have time. 

Sorry that we don't have the md5 of the zip file.

You may ask the authors of the original Wikiart dataset for the download links of each painting:
"Large-scale classification of fine-art paintings: Learning the right metric on the right feature"

Alternatively, you may google or search from https://www.wikiart.org/ for the relevant paintings and download from there to replace the broken images.

**Comment by cs-chan** [comment]
Hi Sotte,

Attached is the broken image and we will update the dataset. Thank you very much. 

 ![l-arlesienne-portrait-of-madame-ginoux-1890](https://user-images.githubusercontent.com/23725126/49864567-afc23280-fe3d-11e8-8209-73f893708a25.jpg)

**Comment by sotte** [comment]
(Sorry for the late reply, I was on vacation).

Great, thanks!
While you're at it maybe also publish the MD5 or SHA of the zip files.
