### ISSUE TITLE
Wikiart Artist pre-trained model link points to CUB instead

### ISSUE THREAD

**Issue by brian36** [cs-chan/ArtGAN#9]
The pre-trained model link for the wikiart Artist model is incorrectly pointing to CUB.

I.e., under the "trained models" section:
https://github.com/cs-chan/ArtGAN/tree/master/ArtGAN#trained-models

"Wikiart Artist - available at this https URL" points to wrong pre-trained model (CUB) - the artist one is not in any of the links.

Where can we find the artist pretrained model?

**Comment by cs-chan** [comment]
Dear Brian, thank you very much. We have updated the link.
